// Code generated by "stringer -type=AddressingMode"; DO NOT EDIT

package gomars

import "fmt"

const _AddressingMode_name = "#$*@{<}>"

var _AddressingMode_index = [...]uint8{0, 1, 2, 3, 4, 5, 6, 7, 8}

func (i AddressingMode) String() string {
	if i >= AddressingMode(len(_AddressingMode_index)-1) {
		return fmt.Sprintf("AddressingMode(%d)", i)
	}
	return _AddressingMode_name[_AddressingMode_index[i]:_AddressingMode_index[i+1]]
}
