// Code generated by "stringer -type=Modifier"; DO NOT EDIT

package gomars

import "fmt"

const _Modifier_name = "fababbaxi"

var _Modifier_index = [...]uint8{0, 1, 2, 3, 5, 7, 8, 9}

func (i Modifier) String() string {
	if i >= Modifier(len(_Modifier_index)-1) {
		return fmt.Sprintf("Modifier(%d)", i)
	}
	return _Modifier_name[_Modifier_index[i]:_Modifier_index[i+1]]
}
