// Code generated by "stringer -type=OpCode"; DO NOT EDIT

package gomars

import "fmt"

const _OpCode_name = "datmovaddsubmuldivmodjmpjmzjmndjnsplcmpseqsnesltldpstpnop"

var _OpCode_index = [...]uint8{0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57}

func (i OpCode) String() string {
	if i >= OpCode(len(_OpCode_index)-1) {
		return fmt.Sprintf("OpCode(%d)", i)
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
